# Generated by Django 4.2.1 on 2023-06-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uas', '0002_paket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jmltiket', models.IntegerField()),
                ('paket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uas.paket')),
            ],
        ),
    ]
